name = "varvar-menu"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGIN = "https://666blackmuxa666.github.io"
TABLES = "15"
SELF_URL = "https://varvar-menu.varvar.workers.dev"

# створіть: npx wrangler kv namespace create DB  → вставте id нижче
[[kv_namespaces]]
binding = "DB"
id = "279c013ca4564083a7f56326a2855bbd"
